services:
  reverse-proxy:
    image: nginx:stable-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /srv/certbot/conf:/etc/letsencrypt/:rw
      - /srv/certbot/www:/var/www/certbot/:rw
      - /srv/certs/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - /srv/certs/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - reverse-proxy
    # command: sh -c "certbot certonly --dry-run --expand --webroot -w /tmp/acme_challenge -d vinoso24.de --text --agree-tos --email steffen.heger@gmail.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    command: sh -c "certbot certonly -d vinoso24.de --text --agree-tos --email steffen.heger@gmail.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    # entrypoint: ""
    # environment:
    #   - TERM=xterm
    volumes:
      - /srv/certbot/conf/:/etc/letsencrypt/:rw
      - /srv/certbot/www/:/var/www/certbot/:rw
      # - /tmp/acme_challenge:/tmp/acme_challenge
