services:
  reverse-proxy:
    image: nginx:stable-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /srv/certbot/conf:/etc/letsencrypt/:rw
      - /srv/certbot/www:/var/www/certbot/:rw
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - /srv/certbot/conf/:/etc/letsencrypt/:rw
      - /srv/certbot/www/:/var/www/certbot/:rw
