# pull the official base image
FROM python:3.9.6-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# install dependencies
RUN python3 -m pip install --upgrade pip
COPY ./requirements.txt /usr/src/app
RUN pip install -r requirements.txt

# copy project
COPY ./vinoso /usr/src/app

EXPOSE 8000

# CMD ["gunicorn --bind 0.0.0.0:8000 /usr/src/app/vinoso/wsgi.py"]
